"""Initial migration.

Revision ID: 4b4fcdfb761d
Revises: 6b171037fbf9
Create Date: 2024-08-04 15:42:02.433123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4fcdfb761d'
down_revision = '6b171037fbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'capture_entries' not in inspector.get_table_names():
        op.create_table('capture_entries',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('handled', sa.Boolean(), nullable=True),
            sa.Column('organized', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('processed_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'project' not in inspector.get_table_names():
        op.create_table('project',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=128), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('status', sa.String(length=64), nullable=True),
            sa.Column('due_date', sa.Date(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'task' not in inspector.get_table_names():
        op.create_table('task',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('content', sa.String(length=256), nullable=False),
            sa.Column('project_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('capture_entries')
    # ### end Alembic commands ###
