name: Deploy to Production

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --global user.email "vadim@example.com"
          git config --global user.name "Vadim Zlatsin"

      - name: Add Heroku remote
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/make-life.git

      - name: Fetch all branches and tags
        run: |
          git fetch --all

      - name: Ensure main branch is checked out
        run: |
          git checkout -b main origin/main || git checkout main

      - name: Merge Heroku main with --allow-unrelated-histories
        run: |
          git merge heroku/main --allow-unrelated-histories || git merge --abort

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push heroku main
