name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          latest_version=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$latest_version/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/test_db" >> $GITHUB_ENV
          echo "FLASK_CONFIG=testing" >> $GITHUB_ENV
          echo "SQLALCHEMY_DATABASE_URI=postgresql://user:password@localhost:5432/test_db" >> $GITHUB_ENV

      - name: Print environment variables for debug
        run: |
          echo "DATABASE_URL=$DATABASE_URL"
          echo "FLASK_CONFIG=$FLASK_CONFIG"
          echo "SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI"

      - name: Start Flask server
        run: |
          nohup flask run &
          sleep 5

      - name: Run tests
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
          FLASK_ENV: testing
          SQLALCHEMY_DATABASE_URI: postgresql://user:password@localhost:5432/test_db
        run: |
          flask db upgrade
          Xvfb :99 -ac &
          export DISPLAY=:99
          pytest
